/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StarsIndexRouteImport } from './routes/stars/index'
import { Route as GiftsIndexRouteImport } from './routes/gifts/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsIndexRoute = StarsIndexRouteImport.update({
  id: '/stars/',
  path: '/stars/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsIndexRoute = GiftsIndexRouteImport.update({
  id: '/gifts/',
  path: '/gifts/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gifts': typeof GiftsIndexRoute
  '/stars': typeof StarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gifts': typeof GiftsIndexRoute
  '/stars': typeof StarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gifts/': typeof GiftsIndexRoute
  '/stars/': typeof StarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gifts' | '/stars'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gifts' | '/stars'
  id: '__root__' | '/' | '/gifts/' | '/stars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GiftsIndexRoute: typeof GiftsIndexRoute
  StarsIndexRoute: typeof StarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars/': {
      id: '/stars/'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/': {
      id: '/gifts/'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GiftsIndexRoute: GiftsIndexRoute,
  StarsIndexRoute: StarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
